---
# discover whether systemd or not
- name: discover systemd
  include_tasks: discover/systemd.yml

# discover whether docker in docker
- name: discover docker in docker
  include_tasks: discover/dind.yml

# load per-os and per distro variables
- name: load ubuntu variables
  include_vars: ubuntu/common.yml
  when: is_ubuntu

- name: load ubuntu trusty variables
  include_vars: ubuntu/trusty.yml
  when: is_ubuntu_trusty_derivative

- name: load ubuntu xenial variables
  include_vars: ubuntu/xenial.yml
  when: is_ubuntu_xenial_derivative

- name: load rhel variables
  include_vars: "{{ var_loop_item }}"
  with_items:
    - redhat/common.yml
    - redhat/rhel7.yml
  loop_control: { loop_var: var_loop_item }

# install redhat repository
- name: install redhat repository
  include_tasks: repo/redhat.yml
  when: is_redhat_derivative

# install ubuntu repository
- name: install ubuntu repository
  include_tasks: repo/ubuntu.yml
  when: is_ubuntu_derivative

# install package
- name: install docker
  package: name=docker-ce state=present

# if we are running in a docker container
- name: include docker-in-docker tasks
  include_tasks: dind.yml
  when: dind

# optionally modify users to be in the docker group
- name: include user modification tasks
  include_tasks: users.yml
  when: docker_users is defined and docker_users is sequence

# manage service
- name: start and enable docker
  service: name=docker state=started enabled=true
  when: not (dind | bool)

- name: stop and disable docker
  service: name=docker state=stopped enabled=false
  when: dind | bool
