---
- name: establish system facts
  set_fact:
    dind: "{{ ansible_virtualization_type == 'docker' }}"
    systemd: "{{ ansible_service_mgr == 'systemd' }}"

# install redhat repository
- name: install redhat repository
  include_tasks: repo/redhat.yml
  when: is_redhat_derivative

# install ubuntu repository
- name: install ubuntu repository
  include_tasks: repo/ubuntu.yml
  when: is_ubuntu_derivative

# install package
- name: install docker
  package: name=docker-ce state=present
  become: true

# if we are running in a docker container
- name: include docker-in-docker tasks
  include_tasks: dind.yml
  when: dind

# optionally modify users to be in the docker group
- name: include user modification tasks
  include_tasks: users.yml
  when: docker_users is defined and docker_users is sequence

# manage service
- name: start and enable docker
  service: name=docker state=started enabled=true
  when: not dind
  become: true

- name: stop and disable docker
  service: name=docker state=stopped enabled=false
  when: dind
  become: true
