---
- name: refresh apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: true

- name: install kernel extras for aufs support
  apt: name=linux-image-extra-virtual state=present cache_valid_time=3600
  when: is_ubuntu_trusty_derivative and not dind
  become: true

- name: install apt https support
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
  become: true

- name: install apt signing key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyserver: "{{ docker_apt_keyserver }}"
    state: present
  become: true

- name: install apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_release }} stable
    filename: docker.list
    update_cache: true
    state: present
  become: true
